### PR TITLE
Improve config modification and lint instructions

### PR DESCRIPTION
**Pull request by be32826**
- Simplify delta loop in README
- Add more comments in README
- Add all targets as defaults
- Lint config.mips64el

### CODE REVIEW

**Comment by AndrewFasano** [comment]
Thanks, I like this. One thing I was seeing with armeb and mips64el - it doesn't seem like building for those targets actually does anything. Maybe I had something set up wrong on my machine? But that's why the mips64el config had some non-linted options and wasn't included in the default list.

**Comment by be32826** [comment]
> One thing I was seeing with armeb and mips64el - it doesn't seem like building for those targets actually does anything.

Apparently it's because the build fails because our kernel version is too old (or our gcc version is too new). This is the relevant upstream commit we're missing: https://github.com/torvalds/linux/commit/bee20031772af3debe8cbaa234528f24c7892e8f.

**Comment by AndrewFasano** [comment]
Gotcha, so we should cherry-pick that commit over to our 4.10 kernel and then merge this?

**Comment by be32826** [comment]
> Gotcha, so we should cherry-pick that commit over to our 4.10 kernel and then merge this?

Yeah, that's a good plan.

**Pull request merged**
